[build]
  publish = "CDSANABRIACF-FINAL"
  command = "echo 'No build command needed - static files'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  CONTACT_EMAIL = "cdsanabriafc@gmail.com"
  CLUB_NAME = "CDSANABRIACF"
  CLUB_LOCATION = "Puebla de Sanabria, Zamora"

[context.deploy-preview.environment]
  CONTACT_EMAIL = "cdsanabriafc@gmail.com"
  CLUB_NAME = "CDSANABRIACF"
  CLUB_LOCATION = "Puebla de Sanabria, Zamora"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
