[build]
  publish = "CDSANABRIACF-FINAL"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Headers para seguridad
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

  # Headers para archivos estáticos
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

  for = "*.jpeg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

  for = "*.gif"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[context.production.environment]
  NODE_ENV = "production"
  CLUB_NAME = "CDSANABRIACF"
  CLUB_EMAIL = "cdsanabriafc@gmail.com"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  CLUB_NAME = "CDSANABRIACF"
  CLUB_EMAIL = "cdsanabriafc@gmail.com"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  CLUB_NAME = "CDSANABRIACF"
  CLUB_EMAIL = "cdsanabriafc@gmail.com"
